# Generated by Django 5.2.17 on 2026-09-14 19:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SigningKey',
            fields=[
                ('fingerprint', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('public_key', models.CharField(max_length=100)),
                ('proof_url', models.URLField(max_length=300)),
                ('proof', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.PositiveBigIntegerField(unique=True)),
                ('github_login', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=32)),
                ('platform_id', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('platform', 'platform_id'), name='unique_mod')],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=80)),
                ('manifest_hash', models.CharField(max_length=64)),
                ('manifest', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='registry.mod')),
            ],
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('published', 'Published'), ('reproduced', 'Reproduced'), ('mismatch', 'Mismatch')], max_length=20)),
                ('payload', models.TextField()),
                ('signature', models.CharField(max_length=100)),
                ('payload_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attestations', to='registry.release')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attestations', to='registry.signingkey')),
            ],
        ),
        migrations.AddField(
            model_name='signingkey',
            name='verifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keys', to='registry.verifier'),
        ),
        migrations.AddConstraint(
            model_name='release',
            constraint=models.UniqueConstraint(fields=('mod', 'version', 'manifest_hash'), name='unique_release_claim'),
        ),
    ]
