<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>UVM</AssemblyName>
    <Version>0.3.0</Version>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <PathMap>$(MSBuildProjectDirectory)/..=/_/source</PathMap>
    <GameManagedPath Condition="'$(GameManagedPath)'==''">$([System.Environment]::GetEnvironmentVariable('CSII_MANAGEDPATH', 'EnvironmentVariableTarget.User'))</GameManagedPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Game"><HintPath>$(GameManagedPath)/Game.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Colossal.Core"><HintPath>$(GameManagedPath)/Colossal.Core.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Colossal.IO.AssetDatabase"><HintPath>$(GameManagedPath)/Colossal.IO.AssetDatabase.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Colossal.Localization"><HintPath>$(GameManagedPath)/Colossal.Localization.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Colossal.Logging"><HintPath>$(GameManagedPath)/Colossal.Logging.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(GameManagedPath)/UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Newtonsoft.Json"><HintPath>$(GameManagedPath)/Newtonsoft.Json.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="System.Net.Http" />
    <Compile Include="../Shared/Scanner.cs" Link="Scanner.cs" />
  </ItemGroup>
</Project>
